modules:
  - name: 'backbone'
  - name: 'routers'

shim:
  'underscore':
    deps: ['jquery']
    exports: '_'
  'backbone':
    deps: ['underscore', 'jquery']
    exports: 'Backbone'
  'jqueryui':
    deps: ['jquery']
    path: 'assets/javascripts/app/jquery-ui-custom.min'
    exports: 'jqueryui'
